<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $properties = [
            // Dublin - Rent
            [
                'title' => '3 Bed Semi-Detached House in Ranelagh',
                'listing_type' => 'rent',
                'property_type' => 'semi-detached',
                'price' => 3200.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1200,
                'address' => '14 Chelmsford Road',
                'town' => 'Ranelagh',
                'county' => 'Dublin',
                'eircode' => 'D06 Y2X8',
                'description' => 'Stunning 3 bedroom semi-detached home in the heart of Ranelagh. Bright and spacious throughout with modern kitchen and two bathrooms. Within walking distance of Ranelagh village and excellent public transport links.',
                'features' => ['parking', 'garden', 'dishwasher', 'washing_machine'],
                'is_featured' => true,
                'status' => 'active',
                'available_from' => '2026-03-01',
                'images' => [
                    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                    'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
                ],
            ],
            // Dublin - Rent
            [
                'title' => '2 Bed Apartment in Docklands',
                'listing_type' => 'rent',
                'property_type' => 'apartment',
                'price' => 2800.00,
                'price_period' => 'per_month',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area_sqft' => 900,
                'address' => 'The Tides, 3 North Wall Quay',
                'town' => 'Dublin 1',
                'county' => 'Dublin',
                'eircode' => 'D01 K8N2',
                'description' => 'Modern 2 bed, 2 bath apartment in Dublin Docklands. Floor-to-ceiling windows with stunning river views. Building has 24hr concierge, gym and rooftop terrace.',
                'features' => ['concierge', 'gym', 'balcony', 'parking', 'dishwasher'],
                'is_featured' => true,
                'status' => 'active',
                'available_from' => '2026-03-15',
                'images' => [
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                ],
            ],
            // Dublin - Sale
            [
                'title' => '4 Bed Detached House in Foxrock',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 1450000.00,
                'price_period' => null,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqft' => 2400,
                'address' => '8 Westminster Road',
                'town' => 'Foxrock',
                'county' => 'Dublin',
                'eircode' => 'D18 HV23',
                'description' => 'Exceptional 4 bedroom detached family home on a large private site in prestigious Foxrock. Stunning garden, double garage, and high-specification finishes throughout.',
                'features' => ['parking', 'garden', 'garage', 'alarm', 'fireplace'],
                'is_featured' => true,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                    'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
                ],
            ],
            // Cork - Rent
            [
                'title' => '2 Bed Apartment in City Centre',
                'listing_type' => 'rent',
                'property_type' => 'apartment',
                'price' => 1800.00,
                'price_period' => 'per_month',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqft' => 750,
                'address' => 'Grand Parade Apartments, 22 Grand Parade',
                'town' => 'Cork City',
                'county' => 'Cork',
                'eircode' => 'T12 AX3Y',
                'description' => 'Modern 2 bedroom apartment in the heart of Cork City. Walking distance to all city amenities, restaurants, and shops.',
                'features' => ['dishwasher', 'washing_machine', 'balcony'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-01',
                'images' => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                    'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
                ],
            ],
            // Cork - Sale
            [
                'title' => '3 Bed Terraced House in Douglas',
                'listing_type' => 'sale',
                'property_type' => 'terraced',
                'price' => 385000.00,
                'price_period' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1100,
                'address' => '47 Maryborough Hill',
                'town' => 'Douglas',
                'county' => 'Cork',
                'eircode' => 'T12 P4X1',
                'description' => 'Well-presented 3 bed terraced home in popular Douglas village. Recently renovated kitchen and bathrooms. South-facing rear garden. Close to all local amenities and schools.',
                'features' => ['garden', 'parking', 'alarm'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
                    'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800',
                ],
            ],
            // Galway - Rent
            [
                'title' => '1 Bed Studio Apartment in Salthill',
                'listing_type' => 'rent',
                'property_type' => 'studio',
                'price' => 1350.00,
                'price_period' => 'per_month',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area_sqft' => 420,
                'address' => 'Salthill Manor, 6 Grattan Road',
                'town' => 'Salthill',
                'county' => 'Galway',
                'eircode' => 'H91 VX23',
                'description' => 'Bright studio apartment in desirable Salthill, steps from the promenade. Perfect for a single professional. Fully furnished and equipped.',
                'features' => ['furnished', 'washing_machine'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-02-28',
                'images' => [
                    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
                ],
            ],
            // Galway - Rent
            [
                'title' => '4 Bed Detached House in Knocknacarra',
                'listing_type' => 'rent',
                'property_type' => 'detached',
                'price' => 2600.00,
                'price_period' => 'per_month',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqft' => 1800,
                'address' => '12 Árd Mhuire',
                'town' => 'Knocknacarra',
                'county' => 'Galway',
                'eircode' => 'H91 DK52',
                'description' => 'Spacious 4 bed detached family home in quiet estate. Large garden, double garage, and excellent school catchment area. Recently decorated throughout.',
                'features' => ['garden', 'garage', 'parking', 'dishwasher', 'alarm'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-04-01',
                'images' => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                ],
            ],
            // Galway - Sale
            [
                'title' => '3 Bed Semi-Detached in Barna',
                'listing_type' => 'sale',
                'property_type' => 'semi-detached',
                'price' => 495000.00,
                'price_period' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1250,
                'address' => '5 An Clochán',
                'town' => 'Barna',
                'county' => 'Galway',
                'eircode' => 'H91 RT4V',
                'description' => 'Superb 3 bed semi-detached in the sought-after village of Barna. Stunning sea views from upstairs. Minutes from the beach and excellent local schools.',
                'features' => ['garden', 'parking', 'sea_views', 'fireplace'],
                'is_featured' => true,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800',
                    'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800',
                ],
            ],
            // Limerick - Rent
            [
                'title' => '2 Bed Apartment in City Centre',
                'listing_type' => 'rent',
                'property_type' => 'apartment',
                'price' => 1500.00,
                'price_period' => 'per_month',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqft' => 700,
                'address' => 'Riverpoint, Lower Mallow Street',
                'town' => 'Limerick City',
                'county' => 'Limerick',
                'eircode' => 'V94 X2K8',
                'description' => 'Contemporary 2 bedroom apartment with stunning river views. Secure underground parking. Walking distance to city centre.',
                'features' => ['parking', 'balcony', 'river_views', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-10',
                'images' => [
                    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                ],
            ],
            // Limerick - Sale
            [
                'title' => '5 Bed Detached in Castletroy',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 590000.00,
                'price_period' => null,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area_sqft' => 2800,
                'address' => '22 Milford Manor',
                'town' => 'Castletroy',
                'county' => 'Limerick',
                'eircode' => 'V94 CF87',
                'description' => 'Impressive 5 bedroom detached family home close to University of Limerick. Tastefully extended and upgraded, this property offers generous living accommodation throughout.',
                'features' => ['garden', 'garage', 'parking', 'alarm', 'fireplace', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
                    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
                ],
            ],
            // Kilkenny - Sale
            [
                'title' => '4 Bed Bungalow on 1 Acre in Thomastown',
                'listing_type' => 'sale',
                'property_type' => 'bungalow',
                'price' => 375000.00,
                'price_period' => null,
                'bedrooms' => 4,
                'bathrooms' => 2,
                'area_sqft' => 1600,
                'address' => 'Kilmaganny Road',
                'town' => 'Thomastown',
                'county' => 'Kilkenny',
                'eircode' => 'R95 X2W4',
                'description' => 'Charming 4 bed bungalow set on approximately 1 acre of mature grounds. Detached double garage, oil central heating, and stunning countryside views.',
                'features' => ['garden', 'garage', 'parking', 'countryside_views', 'fireplace'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800',
                    'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800',
                ],
            ],
            // Waterford - Rent
            [
                'title' => '3 Bed House in Dunmore East',
                'listing_type' => 'rent',
                'property_type' => 'house',
                'price' => 1700.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 1,
                'area_sqft' => 1050,
                'address' => '9 Harbour View',
                'town' => 'Dunmore East',
                'county' => 'Waterford',
                'eircode' => 'X91 PY38',
                'description' => 'Lovely 3 bed family home in the picturesque fishing village of Dunmore East. Sea views from upper floor. Large rear garden with shed.',
                'features' => ['garden', 'sea_views', 'parking'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-04-01',
                'images' => [
                    'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
                ],
            ],
            // Wexford - Sale
            [
                'title' => '3 Bed Semi-Detached in Gorey',
                'listing_type' => 'sale',
                'property_type' => 'semi-detached',
                'price' => 310000.00,
                'price_period' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1100,
                'address' => '18 Meadow Grove',
                'town' => 'Gorey',
                'county' => 'Wexford',
                'eircode' => 'Y25 AX42',
                'description' => 'Well-maintained 3 bed semi in a popular estate. Private rear garden, off-street parking, and within easy reach of Gorey town centre and train station.',
                'features' => ['garden', 'parking'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=800',
                    'https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800',
                ],
            ],
            // Kerry - Rent
            [
                'title' => '2 Bed Cottage in Kenmare',
                'listing_type' => 'rent',
                'property_type' => 'house',
                'price' => 1400.00,
                'price_period' => 'per_month',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqft' => 800,
                'address' => 'Sheen Falls Lane',
                'town' => 'Kenmare',
                'county' => 'Kerry',
                'eircode' => 'V93 KW12',
                'description' => 'Charming renovated stone cottage on the edge of Kenmare town. Mountain and bay views, private garden, and walking distance to all amenities.',
                'features' => ['garden', 'mountain_views', 'fireplace', 'pet_friendly'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-01',
                'images' => [
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
                    'https://images.unsplash.com/photo-1549517045-bc93de075e53?w=800',
                ],
            ],
            // Kerry - Sale
            [
                'title' => '4 Bed Detached in Tralee',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 420000.00,
                'price_period' => null,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqft' => 1900,
                'address' => '3 The Beeches, Oakpark',
                'town' => 'Tralee',
                'county' => 'Kerry',
                'eircode' => 'V92 TK56',
                'description' => 'Spacious 4 bedroom detached home in sought-after Oakpark. Double garage, landscaped gardens, and high quality finishes throughout.',
                'features' => ['garden', 'garage', 'parking', 'alarm'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1600607687939-ce8a6d6cacd4?w=800',
                ],
            ],
            // Kildare - Rent
            [
                'title' => '3 Bed Semi-Detached in Newbridge',
                'listing_type' => 'rent',
                'property_type' => 'semi-detached',
                'price' => 2100.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1150,
                'address' => '24 Beechwood Drive',
                'town' => 'Newbridge',
                'county' => 'Kildare',
                'eircode' => 'W12 AX38',
                'description' => 'Excellent 3 bed semi in quiet estate. Close to Newbridge town, Kildare Village outlet and train station (55 mins to Dublin Heuston).',
                'features' => ['garden', 'parking', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-15',
                'images' => [
                    'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
                    'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800',
                ],
            ],
            // Kildare - Sale
            [
                'title' => '5 Bed Detached in Naas',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 750000.00,
                'price_period' => null,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area_sqft' => 3000,
                'address' => '1 Sallins Road',
                'town' => 'Naas',
                'county' => 'Kildare',
                'eircode' => 'W91 RT2P',
                'description' => 'Stunning executive 5 bed home in Naas town. Recently built to the highest specification with A-rated energy performance, underfloor heating and home automation system.',
                'features' => ['garden', 'garage', 'parking', 'alarm', 'underfloor_heating', 'smart_home'],
                'is_featured' => true,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800',
                    'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
                ],
            ],
            // Meath - Rent
            [
                'title' => '2 Bed Apartment in Navan',
                'listing_type' => 'rent',
                'property_type' => 'apartment',
                'price' => 1600.00,
                'price_period' => 'per_month',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqft' => 720,
                'address' => 'Market Square Apartments, Navan',
                'town' => 'Navan',
                'county' => 'Meath',
                'eircode' => 'C15 AX5T',
                'description' => 'Modern 2 bed apartment in the centre of Navan. Spacious open-plan living, secure parking and excellent transport links to Dublin.',
                'features' => ['parking', 'dishwasher', 'washing_machine'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-01',
                'images' => [
                    'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800',
                ],
            ],
            // Wicklow - Sale
            [
                'title' => '4 Bed Detached in Greystones',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 875000.00,
                'price_period' => null,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqft' => 2100,
                'address' => '15 Rathdown Park',
                'town' => 'Greystones',
                'county' => 'Wicklow',
                'eircode' => 'A63 PK19',
                'description' => 'Immaculate 4 bed detached in the heart of Greystones. Walking distance to beach, DART station, and the vibrant town centre.',
                'features' => ['garden', 'parking', 'alarm', 'sea_views', 'fireplace'],
                'is_featured' => true,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=800',
                    'https://images.unsplash.com/photo-1598902468171-9bddbb3e6c01?w=800',
                ],
            ],
            // Wicklow - Rent
            [
                'title' => '3 Bed House in Bray',
                'listing_type' => 'rent',
                'property_type' => 'terraced',
                'price' => 2400.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1100,
                'address' => '5 Brennanstown Vale',
                'town' => 'Bray',
                'county' => 'Wicklow',
                'eircode' => 'A98 VX42',
                'description' => 'Bright and modern 3 bed terraced home in a quiet cul-de-sac. Walking distance to Bray DART and all local amenities.',
                'features' => ['garden', 'parking', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-04-01',
                'images' => [
                    'https://images.unsplash.com/photo-1575517111839-3a3843ee7f5d?w=800',
                ],
            ],
            // Clare - Sale
            [
                'title' => '3 Bed Semi-Detached in Ennis',
                'listing_type' => 'sale',
                'property_type' => 'semi-detached',
                'price' => 295000.00,
                'price_period' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1100,
                'address' => '12 Claureen View',
                'town' => 'Ennis',
                'county' => 'Clare',
                'eircode' => 'V95 X8K2',
                'description' => 'Well-presented 3 bed semi-detached home in a mature estate in Ennis town. South-facing garden, double-glazed throughout, and recently re-fitted kitchen.',
                'features' => ['garden', 'parking'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1628744448840-55bdb2497bd4?w=800',
                    'https://images.unsplash.com/photo-1625602812206-5ec545ca1231?w=800',
                ],
            ],
            // Tipperary - Rent
            [
                'title' => '3 Bed House in Clonmel',
                'listing_type' => 'rent',
                'property_type' => 'house',
                'price' => 1400.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 1,
                'area_sqft' => 1050,
                'address' => '8 Sarsfield Street',
                'town' => 'Clonmel',
                'county' => 'Tipperary',
                'eircode' => 'E91 PX38',
                'description' => 'Comfortable 3 bed family home in central Clonmel. Close to all local schools, shops and amenities. Private rear garden with shed.',
                'features' => ['garden', 'parking', 'pet_friendly'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-01',
                'images' => [
                    'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800',
                ],
            ],
            // Sligo - Sale
            [
                'title' => '4 Bed Detached in Strandhill',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 390000.00,
                'price_period' => null,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqft' => 1750,
                'address' => '2 Carrowmore View',
                'town' => 'Strandhill',
                'county' => 'Sligo',
                'eircode' => 'F91 TK52',
                'description' => 'Stunning coastal home with ocean views in the surf village of Strandhill. High spec finishes, open-plan living, and landscaped gardens.',
                'features' => ['garden', 'parking', 'sea_views', 'fireplace'],
                'is_featured' => true,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1600873070428-b1e3de3d1395?w=800',
                    'https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800',
                ],
            ],
            // Donegal - Rent
            [
                'title' => '3 Bed House in Letterkenny',
                'listing_type' => 'rent',
                'property_type' => 'semi-detached',
                'price' => 1300.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 1,
                'area_sqft' => 1050,
                'address' => '16 Glencar Road',
                'town' => 'Letterkenny',
                'county' => 'Donegal',
                'eircode' => 'F92 AX18',
                'description' => 'Comfortable 3 bed semi-detached in a popular Letterkenny estate. Private rear garden, good storage, and close to all local amenities.',
                'features' => ['garden', 'parking'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-15',
                'images' => [
                    'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
                ],
            ],
            // Mayo - Sale
            [
                'title' => '3 Bed Bungalow in Westport',
                'listing_type' => 'sale',
                'property_type' => 'bungalow',
                'price' => 280000.00,
                'price_period' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1200,
                'address' => 'Castlebar Road',
                'town' => 'Westport',
                'county' => 'Mayo',
                'eircode' => 'F28 EX41',
                'description' => 'Charming 3 bed bungalow just outside Westport town. Large garden, oil central heating and views of Croagh Patrick.',
                'features' => ['garden', 'parking', 'mountain_views'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
                    'https://images.unsplash.com/photo-1593696140826-c58b021acf8b?w=800',
                ],
            ],
            // Roscommon - Sale
            [
                'title' => '4 Bed Detached on 0.5 Acre in Roscommon Town',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 320000.00,
                'price_period' => null,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqft' => 1900,
                'address' => 'Circular Road',
                'town' => 'Roscommon',
                'county' => 'Roscommon',
                'eircode' => 'F42 TK39',
                'description' => '4 bedroom detached family home on a mature 0.5-acre site close to Roscommon town. Double garage, large garden and BER B2 rating.',
                'features' => ['garden', 'garage', 'parking'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
                ],
            ],
            // Louth - Rent
            [
                'title' => '2 Bed Apartment in Dundalk',
                'listing_type' => 'rent',
                'property_type' => 'apartment',
                'price' => 1450.00,
                'price_period' => 'per_month',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'area_sqft' => 700,
                'address' => 'Market Square, Dundalk',
                'town' => 'Dundalk',
                'county' => 'Louth',
                'eircode' => 'A91 RT6P',
                'description' => 'Contemporary 2 bed apartment in the centre of Dundalk. Secure parking, modern finishes and close to train station (1hr to Dublin Connolly).',
                'features' => ['parking', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-01',
                'images' => [
                    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
                ],
            ],
            // Cavan - Sale
            [
                'title' => '3 Bed Semi-Detached in Cavan Town',
                'listing_type' => 'sale',
                'property_type' => 'semi-detached',
                'price' => 250000.00,
                'price_period' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1050,
                'address' => '7 Lake View Drive',
                'town' => 'Cavan',
                'county' => 'Cavan',
                'eircode' => 'H12 AK4P',
                'description' => '3 bed semi-detached home in a quiet cul-de-sac estate in Cavan town. Recently refurbished with new kitchen and bathrooms. Lake views from upper level.',
                'features' => ['garden', 'parking', 'lake_views'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
                ],
            ],
            // Dublin - Rent (1 bed flat)
            [
                'title' => '1 Bed Flat in Rathmines',
                'listing_type' => 'rent',
                'property_type' => 'flat',
                'price' => 1950.00,
                'price_period' => 'per_month',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area_sqft' => 550,
                'address' => '42 Leinster Road',
                'town' => 'Rathmines',
                'county' => 'Dublin',
                'eircode' => 'D06 AW3X',
                'description' => 'Bright first-floor 1 bed flat in a period property in vibrant Rathmines. Original features retained, modern kitchen, walking distance to city centre.',
                'features' => ['washing_machine', 'pet_friendly'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-01',
                'images' => [
                    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
                ],
            ],
            // Cork - Rent
            [
                'title' => '3 Bed Terraced in Ballincollig',
                'listing_type' => 'rent',
                'property_type' => 'terraced',
                'price' => 2200.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1100,
                'address' => '5 The Meadows',
                'town' => 'Ballincollig',
                'county' => 'Cork',
                'eircode' => 'P31 AK42',
                'description' => 'Spacious 3 bed terraced home in popular Ballincollig. West Cork regional park on the doorstep, excellent schools nearby and easy commute to Cork City.',
                'features' => ['garden', 'parking', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-04-01',
                'images' => [
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                    'https://images.unsplash.com/photo-1592595896616-c37162298647?w=800',
                ],
            ],
            // Dublin - Sale (apartment)
            [
                'title' => '2 Bed Apartment in Clontarf',
                'listing_type' => 'sale',
                'property_type' => 'apartment',
                'price' => 520000.00,
                'price_period' => null,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area_sqft' => 880,
                'address' => '8 Vernon Gardens',
                'town' => 'Clontarf',
                'county' => 'Dublin',
                'eircode' => 'D03 PX12',
                'description' => 'Superb 2 bed, 2 bath apartment in sought-after Clontarf. Sea views, secure parking, and moments from Clontarf DART station and promenade.',
                'features' => ['parking', 'sea_views', 'balcony', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
                ],
            ],
            // Antrim (for reference site match)
            [
                'title' => '3 Bed Semi-Detached in Antrim Town',
                'listing_type' => 'rent',
                'property_type' => 'semi-detached',
                'price' => 1100.00,
                'price_period' => 'per_month',
                'bedrooms' => 3,
                'bathrooms' => 1,
                'area_sqft' => 1000,
                'address' => '12 Castle Way',
                'town' => 'Antrim',
                'county' => 'Antrim',
                'eircode' => 'BT41 2EA',
                'description' => 'Well-maintained 3 bedroom semi-detached home close to Antrim town centre, schools, and public transport.',
                'features' => ['garden', 'parking'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => '2026-03-15',
                'images' => [
                    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                ],
            ],
            // Meath - Sale
            [
                'title' => '4 Bed Detached in Dunboyne',
                'listing_type' => 'sale',
                'property_type' => 'detached',
                'price' => 625000.00,
                'price_period' => null,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area_sqft' => 2000,
                'address' => '6 The Paddocks',
                'town' => 'Dunboyne',
                'county' => 'Meath',
                'eircode' => 'A86 PK18',
                'description' => 'Superb A-rated 4 bed detached home in the commuter village of Dunboyne. 35 minutes to Dublin city centre by train. Landscaped gardens and double garage.',
                'features' => ['garden', 'garage', 'parking', 'alarm', 'dishwasher'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
                ],
            ],
            // Leitrim - Sale
            [
                'title' => '3 Bed Cottage on 2 Acres in Carrick-on-Shannon',
                'listing_type' => 'sale',
                'property_type' => 'house',
                'price' => 245000.00,
                'price_period' => null,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1150,
                'address' => 'Cortober',
                'town' => 'Carrick-on-Shannon',
                'county' => 'Leitrim',
                'eircode' => 'N41 XP38',
                'description' => 'Characterful 3 bed renovated cottage on 2 acres. River Shannon views, detached workshop, and oil central heating. A rare opportunity in this popular tourist town.',
                'features' => ['garden', 'parking', 'river_views', 'fireplace', 'pet_friendly'],
                'is_featured' => false,
                'status' => 'active',
                'available_from' => null,
                'images' => [
                    'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800',
                ],
            ],
        ];

        foreach ($properties as $data) {
            Property::create(array_merge($data, [
                'slug' => Str::slug($data['title']).'-'.Str::random(6),
            ]));
        }
    }
}
